<template><alert type="info">组件依赖于声网 RTC 和 RTM 服务</alert>
<h2 id="属性" tabindex="-1"><a class="header-anchor" href="#属性" aria-hidden="true">#</a> 属性</h2>
<table>
<thead>
<tr>
<th>prop</th>
<th>类型</th>
<th>默认值</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>key</code></td>
<td><code>String</code></td>
<td>-</td>
<td>声网 appId</td>
</tr>
<tr>
<td><code>inviteAwaitDelay</code></td>
<td><code>Number</code></td>
<td><code>3000</code></td>
<td>呼叫等待延迟，默认 3000 ms</td>
</tr>
<tr>
<td><code>userId</code></td>
<td><code>string</code></td>
<td>guid</td>
<td>用户id，默认guid</td>
</tr>
<tr>
<td><code>source</code></td>
<td><code>Array</code></td>
<td><code>[]</code></td>
<td>呼叫列表，格式见下方</td>
</tr>
<tr>
<td><code>total</code></td>
<td><code>Number</code></td>
<td><code>0</code></td>
<td>呼叫列表的长度</td>
</tr>
<tr>
<td><code>type</code></td>
<td><code>Number</code></td>
<td><code>1</code></td>
<td>音视频类型    1 视频 2 语音</td>
</tr>
<tr>
<td><code>maxCallTime</code></td>
<td><code>Number</code></td>
<td><code>40</code></td>
<td>最大呼叫时间 单位 秒</td>
</tr>
</tbody>
</table>
<h2 id="回调" tabindex="-1"><a class="header-anchor" href="#回调" aria-hidden="true">#</a> 回调</h2>
<table>
<thead>
<tr>
<th>回调</th>
<th>参数列表</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>dispatchLoginFailed</code></td>
<td><code>error</code></td>
<td>RTM登录失败的回调</td>
</tr>
<tr>
<td><code>MemberJoined</code></td>
<td><code>memberId</code></td>
<td>用户加入 RTM 频道的回调</td>
</tr>
<tr>
<td><code>MemberLeft</code></td>
<td><code>channelName</code>,<code>args</code></td>
<td>用户离开频道的回调</td>
</tr>
<tr>
<td><code>ConnectionStateChanged</code></td>
<td><code>args</code></td>
<td>链接状态改变的事件回调</td>
</tr>
<tr>
<td><code>MessageFromPeer</code></td>
<td><code>message</code>, <code>peerId</code></td>
<td>收到对方放送的消息的回调</td>
</tr>
<tr>
<td><code>inviteEnd</code></td>
<td>-</td>
<td>调度结束的回调</td>
</tr>
<tr>
<td><code>log</code></td>
<td><code>invite</code>, <code>state</code></td>
<td>每一次状态变更都会触发，用来打日志</td>
</tr>
<tr>
<td><code>networkError</code></td>
<td>-</td>
<td>网络错误的回调</td>
</tr>
<tr>
<td><code>inviteBefore</code></td>
<td><code>inviteInstance</code></td>
<td>发送呼叫邀请前的操作</td>
</tr>
<tr>
<td><code>extra</code></td>
<td><code>extra</code>, <code>invitee</code></td>
<td>呼叫之前的准备工作，可以处理一些传递数据</td>
</tr>
<tr>
<td><code>inviteTimeout</code></td>
<td><code>inviteInstance</code></td>
<td>呼叫实例超时的回调</td>
</tr>
<tr>
<td><code>playChange</code></td>
<td><code>e</code></td>
<td>播放状态更新</td>
</tr>
<tr>
<td><code>netChange</code></td>
<td><code>e</code></td>
<td>网络状态更新</td>
</tr>
<tr>
<td><code>inviteAccept</code></td>
<td><code>channel</code>, <code>target</code>,<code>id</code></td>
<td>接收邀请的回调</td>
</tr>
<tr>
<td><code>streamSuccess</code></td>
<td><code>uid</code>,<code>url</code></td>
<td>音视频流准备完毕的回调</td>
</tr>
<tr>
<td><code>streamRotation</code></td>
<td><code>rotation</code>, <code>uid</code></td>
<td>流发生旋转的回调</td>
</tr>
<tr>
<td><code>streamAdded</code></td>
<td><code>uid</code></td>
<td>流加入的回调</td>
</tr>
<tr>
<td><code>streamSubscribe</code></td>
<td><code>url</code>, <code>uid</code></td>
<td>流订阅成功</td>
</tr>
<tr>
<td><code>streamError</code></td>
<td><code>code</code></td>
<td>流发送错误</td>
</tr>
<tr>
<td><code>streamUpdate</code></td>
<td><code>url</code>, <code>uid</code></td>
<td>流更新的回调</td>
</tr>
<tr>
<td><code>streamRemoved</code></td>
<td><code>relatedId</code>, <code>callTime</code>, <code>target</code>, <code>inviteTime</code></td>
<td>音视频流移除的回调</td>
</tr>
</tbody>
</table>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> 方法</h2>
<alert type="info">方法可以通过 `selectComponent(id)` 调用</alert>
<table>
<thead>
<tr>
<th>方法名</th>
<th>参数</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>sendMessageByPeer</code></td>
<td><code>message</code>, <code>peerId</code></td>
<td>发送点对点消息</td>
</tr>
<tr>
<td><code>reAgoraChannel</code></td>
<td><code>uid</code>,<code>channel</code></td>
<td>重新加入频道</td>
</tr>
<tr>
<td><code>onClose</code></td>
<td><code>isActive</code>,<code>isSend</code></td>
<td>挂断方法</td>
</tr>
<tr>
<td><code>hasEnd</code></td>
<td>-</td>
<td>判断是否邀请完毕的方法</td>
</tr>
</tbody>
</table>
<h2 id="插槽" tabindex="-1"><a class="header-anchor" href="#插槽" aria-hidden="true">#</a> 插槽</h2>
<table>
<thead>
<tr>
<th>插槽名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td><code>empty</code></td>
<td>空状态插槽，会在没有开始音视频时渲染，开始音视频后销毁</td>
</tr>
<tr>
<td><code>content</code></td>
<td>主内容插槽</td>
</tr>
<tr>
<td><code>footer</code></td>
<td>底部插槽</td>
</tr>
</tbody>
</table>
</template>
